void updateScreen();
void read_sensors();
void toggleTimer();
void clearScreen();
void resetTimer();
void adjustTime(bool increase);
void changeScreenState();
void print_display_2();
void initialize_sht40();
void resetTimer();
void adjustTime(bool increase);
void setup();
bool checkButtons();
void displayTime();
void loop();
void drawScreen1();
void drawScreen2();
void drawScreen3();
void drawScreen4();
void drawScreen5();
void drawScreen6();
void drawScreen7();
void drawScreen8();
void drawScreen9();
void drawScreen10();
void drawScreen11();
void drawScreen12();
